### ISSUE TITLE
Deploy returns 404 and fails, but actually deployed successfully on Connect

### ISSUE THREAD

**Issue by andrie** [rstudio/actions#18]
I have deployed an app on two different Connect servers, and in both cases the deployment succeeds, but the Connect return code is 404, so github actions think that the deployment fails.

Here is a (redacted) version of the output:

```
Run rstudio/actions/connect-publish@main
  with:
    url: https://***@xxxxxxxxxxxxxxxx.com
    access-type: logged_in
    force: true
    require-vanity-path: true
    dir: ./team-admin-call-classroom-api:/team-admin-call-classroom-api
  
    show-logs: false
    update-env: true
  env:
    APP_DIR: team-admin-call-classroom-api
    RSCONNECT_URL: https://xxxxxxxxxxxx.com
    RSCONNECT_USERNAME: andrie
    CONNECT_API_KEY_RSTUDIOSERVICES: ***
    CONNECT_ENV_SET_COLORADO_CONNECT_API_KEY: ***
publishing ./team-admin-call-classroom-api to https://xxxxxxxxx.com/team-admin-call-classroom-api/
     id: 1720
   name: team-admin-call-classroom-api
   guid: xxxxxx
  title: 
Error: Error: Request failed with status code 404

connect-publish results:
      id: -1
     dir: ./team-admin-call-classroom-api
     url: 
  status: ✘

Error: Error: unsuccessful publish of dirs=./team-admin-call-classroom-api
```

**Comment by meatballhat** [comment]
Do you know if you get different behavior when deploying via the IDE, or with [rsconnect](https://github.com/rstudio/rsconnect) or [rsconnect-python](https://github.com/rstudio/rsconnect-python)?

**Comment by andrie** [comment]
I deploy frequently to both these servers, using a combination of push-button and git-backed deployment, and never get any problems.  I've never tried `rsconnect-python`.  I've also frequently used `rsconnect::deployApp()` and also don't tend to have any problems.

**Comment by meatballhat** [comment]
Thank you, @andrie!
