### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by aodhan-domhnaill** [rstudio/actions#33]
I have some internal users that are deploy R like https://www.r-bloggers.com/2020/12/rstudio-connect-1-8-6-deployment-api/. I'm looking to switch them over to Github Actions, but I don't seem much going on here lately.

Is this project dead? Are there better ones to use?

**Comment by aronatkins** [comment]
This project is not dead, but we have not given it much publicity.

Is the connect-publish action suitable for your situation? What is missing?

**Comment by aodhan-domhnaill** [comment]
Yeah.  I think the connect-publish covers what I want. Just checking that support won't disappear or the repo won't be archived.
